name: native_media_example
description: Android playback example for the ppplayer native library provider.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  media_kit: ^1.2.3
  media_kit_video: ^2.0.1
  ppplayer_media_kit_libs_android_video:
    path: ../
dev_dependencies:
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
